version: "3"

services:
  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - phpfpm

  phpfpm:
    image: phalconphp/php-fpm:7
    volumes:
        - ./src:/var/www/html
    links:
      - pgsql
      - redis

  pgsql:
    image: postgres
    volumes:
      - ./pginit:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "ITookanArrowintheKnee"
      POSTGRES_USER: "gog"

  redis:
    image: redis
    ports:
      - 6379:6379

